import React,{useEffect,useState} from 'react';
import {SafeAreaView,View,Text,TextInput,Pressable,ScrollView,StyleSheet,Modal,Switch,ActivityIndicator,RefreshControl,Linking,Alert} from 'react-native';
import * as SecureStore from 'expo-secure-store';
import {StatusBar} from 'expo-status-bar';
const currency=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format((n||0)/100);
const categories=['Catering','Photography','Decoration','Venue','Entertainment','Other'];
const human=s=>s.replaceAll('_',' ');
export default function App(){
 const [url,setUrl]=useState(''),[key,setKey]=useState(''),[connected,setConnected]=useState(false),[data,setData]=useState(null),[page,setPage]=useState('Events'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[form,setForm]=useState(null),[values,setValues]=useState({});
 useEffect(()=>{Promise.all([SecureStore.getItemAsync('josh-url'),SecureStore.getItemAsync('josh-key')]).then(([u,k])=>{if(u&&k){setUrl(u);setKey(k);setConnected(true)}}).catch(()=>setError('Could not read secure device storage.'))},[]);
 async function request(path,body){const r=await fetch(url.replace(/\/$/,'')+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});let b;try{b=await r.json()}catch{throw new Error('The website returned a sign-in page instead of the app API. Check the deployment access policy.')}if(!r.ok)throw new Error(b.error||'Request failed');return b}
 async function refresh(){setBusy(true);setError('');try{setData(await request('/api/business'))}catch(e){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{if(connected)void refresh()},[connected]);
 async function connect(){setError('');try{const u=new URL(url);if(u.pathname!=='/'||u.search||u.hash||u.username||u.password)throw new Error('Enter only the website origin.');if(u.protocol!=='https:'&&!(__DEV__&&u.protocol==='http:'))throw new Error('Use your secure HTTPS website address.');if(!/^[a-f0-9]{64}$/.test(key))throw new Error('Paste the 64-character mobile key from your website account.');setBusy(true);const snapshot=await request('/api/business');if(!snapshot.account)throw new Error('Complete account setup on the website first.');await SecureStore.setItemAsync('josh-url',u.origin);await SecureStore.setItemAsync('josh-key',key);setUrl(u.origin);setData(snapshot);setConnected(true)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function disconnect(){await SecureStore.deleteItemAsync('josh-key');await SecureStore.deleteItemAsync('josh-url');setKey('');setConnected(false);setData(null)}
 async function act(action,payload){setBusy(true);setError('');try{await request('/api/actions',{action,data:payload,version:data.version});setForm(null);await refresh()}catch(e){setError(e.message);if(e.message.includes('changed')){const snapshot=await request('/api/business');setData(snapshot)}}finally{setBusy(false)}}
 const items=data?.items||[],of=k=>items.filter(i=>i.kind===k),role=data?.account?.role,admin=role==='admin',vendor=role==='vendor',customer=role==='customer',events=of('event');
 const eventName=id=>events.find(e=>e.id===id)?.data.name||'Event';
 const option=(value,label=value)=>({value,label});
 const eventField={key:'event',label:'Event',options:events.map(e=>option(e.id,e.data.name+' · '+e.data.date))};
 function open(action,title,fields,defaults={}){setError('');setValues(defaults);setForm({action,title,fields})}
 const field=(key,label,type='text')=>({key,label,type});
 const button=(label,onPress,secondary=false,disabled=false)=><Pressable accessibilityRole="button" disabled={disabled||busy} onPress={onPress} style={[s.button,secondary&&s.secondary,(disabled||busy)&&{opacity:.45}]}><Text style={[s.buttonText,secondary&&{color:'#543ed4'}]}>{label}</Text></Pressable>;
 const empty=label=><View style={s.card}><Text style={s.subheading}>{label}</Text><Text style={s.muted}>Updates will appear here as your event progresses.</Text></View>;
 const eventForm=()=>open('create_event','Plan your event',[field('name','Event / customer name'),field('phone','Contact phone','phone-pad'),{key:'type',label:'Occasion',options:['Wedding','Birthday','Corporate function','Other celebration'].map(x=>option(x))},field('date','Date (YYYY-MM-DD)'),field('city','City / venue area'),field('guests','Guest count','numeric'),field('budget','Target budget (INR)','decimal-pad'),{key:'services',label:'Services needed',multi:true,options:categories.map(x=>option(x))},field('notes','Additional requests')],{city:'Vellore',type:'Wedding',services:['Catering'],notes:''});
 const quoteForm=event=>open('submit_quote','Submit your quote',[eventField,field('amount','Total including taxes (INR)','decimal-pad'),field('advance','Advance required (%)','decimal-pad'),field('validUntil','Valid until (YYYY-MM-DD)'),field('scope','Included services and quantities'),field('exclusions','Exclusions')],{event,advance:'30',exclusions:'None'});
 const tabs=vendor?['Events','Quotes','Tasks','Issues','Inbox','Account']:admin?['Events','Packages','Cash flow','Tasks','Inbox','Account']:['Events','Packages','Payments','Inbox','Account'];
 if(!connected)return <SafeAreaView style={s.safe}><StatusBar style="dark"/><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Text style={s.logo}>JOSH EVENTS</Text><Text style={s.heading}>Your events.<Text>{'\n'}In good hands.</Text></Text><Text style={s.muted}>Connect to your JOSH Events website account. In the website, open Account → Generate mobile access key. Keys expire after 7 days and can be revoked there.</Text><Text style={s.label}>Your JOSH Events website</Text><TextInput style={s.input} value={url} onChangeText={setUrl} autoCapitalize="none" keyboardType="url" placeholder="https://your-site.example"/><Text style={s.label}>Mobile access key</Text><TextInput style={s.input} value={key} onChangeText={setKey} autoCapitalize="none" secureTextEntry autoCorrect={false}/>{error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}{button('Connect securely',connect)}<Text style={s.muted}>No payment is taken in this app. Initial account setup uses the website’s supported sign-in flow.</Text></ScrollView></SafeAreaView>;
 return <SafeAreaView style={s.safe}><StatusBar style="dark"/><View style={s.header}><Text style={s.logo}>JOSH EVENTS</Text><Text style={s.muted}>{role||'Connecting'}</Text></View><ScrollView horizontal showsHorizontalScrollIndicator={false} style={s.tabs} contentContainerStyle={{gap:8,paddingHorizontal:20}}>{tabs.map(t=><Pressable accessibilityRole="tab" accessibilityState={{selected:page===t}} key={t} onPress={()=>setPage(t)} style={[s.tab,page===t&&s.activeTab]}><Text style={{color:page===t?'white':'#6f7183'}}>{t}</Text></Pressable>)}</ScrollView><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={busy} onRefresh={refresh}/>}><Text style={s.heading}>{page}</Text>{error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}{!data&&<ActivityIndicator color="#543ed4"/>}
 {page==='Events'&&<>{!vendor&&button('New event request',eventForm)}{events.length?events.map(e=><View style={s.card} key={e.id}><Text style={s.eyebrow}>{e.data.type}</Text><Text style={s.subheading}>{e.data.name}</Text><Text style={s.muted}>{e.data.date} · {e.data.guests} guests · {e.data.city}</Text><Text style={s.status}>{human(e.status)}</Text><Text style={s.body}>{e.data.services.join(', ')}</Text>{vendor&&['enquiry','quoting'].includes(e.status)&&button('Submit quote',()=>quoteForm(e.id))}{admin&&e.status==='awaiting_advance'&&button('Confirm booking',()=>act('confirm_event',{id:e.id}))}{!vendor&&!['cancelled','completed','cancellation_requested'].includes(e.status)&&button('Request cancellation',()=>open('request_cancellation','Cancellation request',[field('reason','Reason')],{id:e.id}),true)}</View>):empty('No events yet')}</>}
 {page==='Packages'&&<>{of('package').length?of('package').map(p=><View style={s.card} key={p.id}><Text style={s.eyebrow}>{p.data.name}</Text><Text style={s.subheading}>{eventName(p.event)}</Text><Text style={s.price}>{currency(p.data.total)}</Text><Text style={s.muted}>Advance {currency(p.data.advance)} · {p.data.guests} guests</Text><Text style={s.status}>{p.status}</Text><Text style={s.label}>Included</Text><Text style={s.body}>{p.data.inclusions}</Text><Text style={s.label}>Excluded</Text><Text style={s.body}>{p.data.exclusions}</Text><Text style={s.label}>Booking terms</Text><Text style={s.body}>{p.data.terms}</Text>{p.data.policySnapshot&&<><Text style={s.label}>Cancellation and refunds</Text><Text style={s.body}>{p.data.policySnapshot.cancellation}</Text><Text style={s.label}>Business terms</Text><Text style={s.body}>{p.data.policySnapshot.terms}</Text></>}{(customer||p.owner===data.account.id)&&p.status==='published'&&button('Review and approve',()=>open('approve_package','Approve package',[{key:'acknowledge',label:'I accept the package, price and displayed booking terms',type:'boolean'}],{id:p.id,acknowledge:false}))}</View>):empty('No packages yet')}</>}
 {page==='Quotes'&&<>{of('quote').map(q=><View key={q.id} style={s.card}><Text style={s.subheading}>{eventName(q.event)}</Text><Text style={s.price}>{currency(q.data.amount)}</Text><Text style={s.body}>{q.data.scope}</Text><Text style={s.muted}>Valid until {q.data.validUntil} · Advance {q.data.advance}%</Text></View>)}{!of('quote').length&&empty('No quotes submitted')}</>}
 {page==='Cash flow'&&<>{(data.finances||[]).map(f=><View key={f.event} style={s.card}><Text style={s.subheading}>{eventName(f.event)}</Text>{Object.entries({received:'Received',cash:'Cash available',customerBalance:'Customer balance',vendorOutstanding:'Vendor obligations',margin:'Expected gross margin'}).map(([k,label])=><View key={k} style={s.row}><Text style={s.body}>{label}</Text><Text style={s.body}>{currency(f[k])}</Text></View>)}</View>)}<Text style={s.muted}>Record external transactions in the website’s Cash flow screen.</Text></>}
 {page==='Payments'&&<>{of('payment').map(p=><View style={s.card} key={p.id}><Text style={s.subheading}>{human(p.data.type)}</Text><Text style={s.price}>{currency(p.data.amount)}</Text><Text style={s.body}>{p.data.reference}</Text><Text style={s.muted}>{p.data.receiptNumber} · {p.created.slice(0,10)}</Text></View>)}{!of('payment').length&&empty('No payment records yet')}<Text style={s.muted}>These are records of external transactions. The app does not transfer money.</Text></>}
 {page==='Tasks'&&<>{of('task').map(t=><View key={t.id} style={s.card}><Text style={s.subheading}>{t.data.name}</Text><Text style={s.muted}>{eventName(t.event)} · Due {t.data.due}</Text><Text style={s.status}>{t.status}</Text>{t.status==='pending'&&(admin||t.data.assignee===data.account.id)&&button('Mark complete',()=>act('complete_task',{id:t.id}),true)}</View>)}{!of('task').length&&empty('No tasks assigned')}</>}
 {page==='Issues'&&<>{of('issue').map(i=><View key={i.id} style={s.card}><Text style={s.subheading}>{i.data.reason}</Text><Text style={s.body}>{i.data.evidence}</Text><Text style={s.price}>{currency(i.data.amount)}</Text><Text style={s.status}>{i.status}</Text>{i.data.response&&<Text style={s.body}>{i.data.response}</Text>}{['open','responded'].includes(i.status)&&button('Respond',()=>open('respond_issue','Respond to issue',[field('response','Your response and evidence')],{id:i.id}))}</View>)}{!of('issue').length&&empty('No service issues')}</>}
 {page==='Inbox'&&<>{of('notification').map(n=><View key={n.id} style={s.card}><Text style={s.body}>{n.data.message}</Text><Text style={s.muted}>{new Date(n.created).toLocaleString()}</Text>{n.status==='unread'&&button('Mark read',()=>act('read_notification',{id:n.id}),true)}</View>)}{!of('notification').length&&empty('You’re all caught up')}<Text style={s.muted}>In-app updates only. Push notifications, SMS and email are not connected.</Text></>}
 {page==='Account'&&<><View style={s.card}><Text style={s.subheading}>{data?.account?.name}</Text><Text style={s.body}>{data?.account?.email}</Text><Text style={s.status}>{role}</Text>{button('Open website',()=>Linking.openURL(url),true)}{button('Contact support',()=>open('support','Contact support',[field('subject','Subject'),field('message','Message')]),true)}{button('Request account deletion',()=>open('deletion_request','Request deletion',[field('reason','Request details')]),true)}{button('Disconnect this device',disconnect,true)}</View>{vendor&&!of('vendor').length&&button('Register your business',()=>open('register_vendor','Vendor registration',[field('name','Business name'),field('phone','Phone','phone-pad'),field('city','Service area'),{key:'category',label:'Service category',options:categories.map(x=>option(x))},field('portfolio','HTTPS portfolio URL'),field('description','Services and experience')],{city:'Vellore',category:'Catering'}))}{vendor&&button('Set availability',()=>open('availability','Set a date',[field('date','Date (YYYY-MM-DD)'),{key:'available',label:'Available for bookings',type:'boolean'}],{available:true}))}{of('vendor').map(v=><View key={v.id} style={s.card}><Text style={s.subheading}>{v.data.name}</Text><Text style={s.status}>{v.status}</Text><Text style={s.body}>{v.data.review||'Awaiting review'}</Text></View>)}</>}
 </ScrollView><Modal visible={!!form} animationType="slide" onRequestClose={()=>{if(!busy)setForm(null)}}><SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Text style={s.heading}>{form?.title}</Text>{form?.fields.map(f=><View key={f.key}><Text style={s.label}>{f.label}</Text>{f.options?<View style={s.choices}>{f.options.map(o=>{const checked=f.multi?(values[f.key]||[]).includes(o.value):values[f.key]===o.value;return <Pressable accessibilityRole={f.multi?'checkbox':'radio'} accessibilityState={{checked}} key={o.value} style={[s.choice,checked&&s.choiceActive]} onPress={()=>setValues(v=>({...v,[f.key]:f.multi?(checked?(v[f.key]||[]).filter(x=>x!==o.value):[...(v[f.key]||[]),o.value]):o.value}))}><Text style={{color:checked?'#543ed4':'#7b8190'}}>{checked?'✓ ':''}{o.label}</Text></Pressable>})}</View>:f.type==='boolean'?<Switch value={!!values[f.key]} onValueChange={value=>setValues(v=>({...v,[f.key]:value}))}/>:<TextInput style={s.input} value={String(values[f.key]??'')} onChangeText={text=>setValues(v=>({...v,[f.key]:text}))} keyboardType={['numeric','decimal-pad','phone-pad'].includes(f.type)?f.type:'default'} autoCapitalize={f.key==='portfolio'?'none':'sentences'}/>}</View>)}{error&&<Text style={s.error}>{error}</Text>}{button('Save and continue',()=>act(form.action,values))}{button('Cancel',()=>setForm(null),true)}</ScrollView></SafeAreaView></Modal></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f6f7f9'},content:{padding:22,paddingBottom:50,gap:12},header:{paddingHorizontal:22,paddingVertical:16,backgroundColor:'#fff',flexDirection:'row',justifyContent:'space-between'},logo:{fontSize:18,fontWeight:'800',letterSpacing:2,color:'#543ed4'},heading:{fontSize:31,fontWeight:'700',color:'#242b3b',marginVertical:14},subheading:{fontSize:20,fontWeight:'600',color:'#252d3c'},body:{fontSize:16,color:'#485264',lineHeight:25},muted:{fontSize:14,color:'#808797',lineHeight:22},label:{fontSize:15,fontWeight:'600',color:'#566071',marginTop:14,marginBottom:8},input:{borderWidth:1,borderColor:'#dfe2e9',borderRadius:9,padding:14,backgroundColor:'white',fontSize:16,color:'#252d3c'},button:{backgroundColor:'#543ed4',padding:15,borderRadius:8,marginVertical:7,alignItems:'center'},secondary:{backgroundColor:'#f0edff'},buttonText:{fontSize:16,fontWeight:'600',color:'white'},error:{padding:13,backgroundColor:'#fff0eb',color:'#a34430',fontSize:15,lineHeight:23},card:{backgroundColor:'white',borderRadius:12,padding:22,borderWidth:1,borderColor:'#e8eaf0',marginVertical:5,gap:9},eyebrow:{fontSize:12,color:'#9384c0',textTransform:'uppercase',letterSpacing:1},status:{color:'#7360ac',backgroundColor:'#f2effd',padding:7,borderRadius:6,alignSelf:'flex-start',fontSize:13,textTransform:'capitalize'},price:{fontSize:27,fontWeight:'700',color:'#543ed4'},tabs:{maxHeight:58,paddingVertical:10,backgroundColor:'white'},tab:{paddingHorizontal:15,paddingVertical:9,borderRadius:7,backgroundColor:'#f6f7f9'},activeTab:{backgroundColor:'#543ed4'},row:{flexDirection:'row',justifyContent:'space-between',gap:12},choices:{gap:8},choice:{padding:13,borderWidth:1,borderColor:'#e0e3ea',borderRadius:7,backgroundColor:'white'},choiceActive:{backgroundColor:'#eeeaff',borderColor:'#9a8be0'}});
