import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
mkdirSync('work',{recursive:true});
import ts from 'typescript';
writeFileSync('work/business-test.mjs',ts.transpileModule(readFileSync('lib/business.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText);
const {command,dataset,visible,finance}=await import('../work/business-test.mjs');
const sql=new DatabaseSync(':memory:');
for(const file of ['drizzle/0000_aspiring_changeling.sql','drizzle/0001_skinny_black_panther.sql']) sql.exec(readFileSync(file,'utf8'));
const db={prepare(query){let bindings=[];return {bind(...v){bindings=v;return this},async run(){const r=sql.prepare(query).run(...bindings);return {meta:{changes:Number(r.changes)}}},async first(){return sql.prepare(query).get(...bindings)||null},async all(){return {results:sql.prepare(query).all(...bindings)}}}},async batch(stmts){sql.exec('BEGIN');try{const out=[];for(const s of stmts)out.push(await s.run());sql.exec('COMMIT');return out}catch(e){sql.exec('ROLLBACK');throw e}}};
const admin={id:'admin',name:'Coordinator',email:'admin@example.test',role:'admin'},customer={id:'customer',name:'Customer',email:'customer@example.test',role:'customer'},other={id:'other',name:'Other',email:'other@example.test',role:'customer'},vendor={id:'vendor',name:'Vendor',email:'vendor@example.test',role:'vendor'};
for(const a of [admin,customer,other,vendor])sql.prepare('INSERT INTO members VALUES (?,?,?,?,?)').run(a.id,a.email,a.name,a.role,new Date().toISOString());
const go=async(a,action,data)=>command(db,a,{action,data,version:(await dataset(db)).version});
const fail=async(a,action,data,message)=>assert.rejects(()=>go(a,action,data),new RegExp(message));
const event=(await go(customer,'create_event',{name:'Test wedding',phone:'9000000000',type:'Wedding',date:'2027-12-12',city:'Vellore',guests:100,budget:200000,services:['Catering'],notes:''})).id;
await fail(other,'request_cancellation',{id:event,reason:'Attack'},'not yours');
const v=(await go(vendor,'register_vendor',{name:'Test Caterer',phone:'9000000000',city:'Vellore',category:'Catering',portfolio:'https://example.com',description:'Catering'})).id;
await fail(vendor,'submit_quote',{event,amount:100000,advance:30,scope:'100 guests',exclusions:'None',validUntil:'2027-12-01'},'must be approved');
await fail(customer,'review_vendor',{id:v,status:'approved',reason:'Attack'},'Administrator');
await go(admin,'review_vendor',{id:v,status:'approved',reason:'Portfolio and service area checked'});
const q=(await go(vendor,'submit_quote',{event,amount:100000,advance:30,scope:'100 guests',exclusions:'None',validUntil:'2027-12-01'})).id;
const pkg=(await go(admin,'create_package',{event,name:'Essential',quotes:[q],markup:15,advancePercent:40,inclusions:'Catering for 100',exclusions:'Venue',terms:'Test agreed terms'})).id;
await fail(admin,'publish_package',{id:pkg},'policies');
await go(admin,'settings',{supportEmail:'help@example.test',supportPhone:'9000000000',privacy:'Test approved privacy',cancellation:'Test agreed cancellation terms',terms:'Test approved terms',published:true});
await go(admin,'publish_package',{id:pkg});
await fail(customer,'approve_package',{id:pkg},'acknowledge');
await go(customer,'approve_package',{id:pkg,acknowledge:true});
await fail(admin,'confirm_event',{id:event},'advance');
const d=await dataset(db),f=finance(d.items.find(i=>i.id===event),d.items);assert.equal(f.packageTotal,11500000);assert.equal(f.requiredAdvance,4600000);
await go(admin,'payment',{event,type:'receipt',amount:46000,reference:'UTR-ONE',vendor:'',note:'Bank receipt'});
await fail(admin,'payment',{event,type:'receipt',amount:1,reference:'UTR-ONE',vendor:'',note:'Duplicate'},'already recorded');
await go(admin,'confirm_event',{id:event});
await fail(admin,'complete_event',{id:event},'has not arrived');
await fail(admin,'payment',{event,type:'vendor_payment',amount:50000,reference:'UTR-TWO',vendor:vendor.id,note:'Advance'},'Insufficient');
await go(admin,'payment',{event,type:'vendor_payment',amount:30000,reference:'UTR-TWO',vendor:vendor.id,note:'Advance paid'});
const issue=(await go(customer,'report_issue',{event,quote:q,amount:5000,reason:'Missing item',evidence:'Agreed scope and receipt'})).id;
await fail(admin,'resolve_issue',{id:issue,decision:'approved',reason:'Decision'},'vendor response');
await fail(admin,'payment',{event,type:'vendor_payment',amount:100,reference:'UTR-THREE',vendor:vendor.id,note:'Settlement'},'Resolve');
await go(vendor,'respond_issue',{id:issue,response:'Confirmed missing item'});
await go(admin,'resolve_issue',{id:issue,decision:'approved',reason:'Agreed shortfall'});
const after=await dataset(db);assert.equal(visible(other,after).items.some(i=>i.id===event),false);assert.equal(visible(customer,after).items.some(i=>i.kind==='quote'),false);assert.equal(visible(customer,after).items.find(i=>i.id===pkg).data.cost,undefined);assert.equal(visible(customer,after).items.find(i=>i.id===pkg).data.services[0].id,q);assert.equal(visible(vendor,after).items.find(i=>i.id===event).data.phone,undefined);
await assert.rejects(()=>command(db,admin,{action:'settings',data:{supportEmail:'help@example.test',supportPhone:'9000000000',privacy:'p',cancellation:'c',terms:'t',published:true},version:0}),/changed/);
console.log('PASS: account isolation, role enforcement, vendor approval, quote/package workflow, consent, funding gates, duplicate references, payout limits, issue response/review, price confidentiality and stale-update rejection');


const restoreId=crypto.randomUUID(),backupPath=`work/backup-${restoreId}.json`,restorePath=`work/restore-${restoreId}.sql`;
writeFileSync(backupPath,JSON.stringify({format:'josh-events-export',schemaVersion:1,exportedAt:new Date().toISOString(),...after}));
execFileSync(process.execPath,['scripts/prepare-restore.mjs',backupPath,restorePath]);
const restored=new DatabaseSync(':memory:');for(const file of ['drizzle/0000_aspiring_changeling.sql','drizzle/0001_skinny_black_panther.sql'])restored.exec(readFileSync(file,'utf8'));
restored.exec(readFileSync(restorePath,'utf8'));restored.exec(readFileSync(restorePath,'utf8'));
assert.equal(restored.prepare('SELECT COUNT(*) n FROM business').get().n,after.items.length);
console.log('PASS: backup restore round-trip preserves records and duplicate restore does not duplicate IDs');
