import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '../app/chatgpt-auth';
import {recordsDb} from '../db/records';
import {BusinessError,type Actor} from './business';
export async function identity(){const user=await getChatGPTUser();if(!user)throw new BusinessError('Please sign in to continue.',401);return user;}
export async function account():Promise<Actor|null>{const user=await identity();const db=recordsDb();const adminEmail=(env as any).JOSH_ADMIN_EMAIL?.trim().toLowerCase();if(adminEmail&&user.email.toLowerCase()===adminEmail){await db.prepare("INSERT INTO members(id,email,name,role,created) VALUES (?,?,?,'admin',?) ON CONFLICT(id) DO UPDATE SET role='admin',email=excluded.email,name=excluded.name").bind(user.userId,user.email,user.displayName,new Date().toISOString()).run();return {id:user.userId,email:user.email,name:user.displayName,role:'admin'};}const member=await db.prepare('SELECT id,email,name,role FROM members WHERE id=?').bind(user.userId).first<Actor>();if(member?.role==='admin')throw new BusinessError('Administrator configuration has changed. Contact the site owner.',403);return member;}
export async function hashToken(token:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token)))).map(n=>n.toString(16).padStart(2,'0')).join('');}
export async function actor(request?:Request):Promise<Actor>{const bearer=request?.headers.get('authorization');if(bearer){if(!/^Bearer [a-f0-9]{64}$/.test(bearer))throw new BusinessError('Invalid mobile access token.',401);const row=await recordsDb().prepare('SELECT m.id,m.email,m.name,m.role FROM mobile_tokens t JOIN members m ON m.id=t.owner WHERE t.hash=? AND t.expires>?').bind(await hashToken(bearer.slice(7)),new Date().toISOString()).first<Actor>();if(!row)throw new BusinessError('Mobile access expired or revoked. Connect again from your website account.',401);if(row.role==='admin'&&row.email.toLowerCase()!==(env as any).JOSH_ADMIN_EMAIL?.trim().toLowerCase())throw new BusinessError('Administrator access is not available.',403);return row;}const a=await account();if(!a)throw new BusinessError('Complete your account setup.',403);return a;}
export function sameOrigin(request:Request){const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)throw new BusinessError('Invalid request origin',403);if(!request.headers.get('content-type')?.startsWith('application/json'))throw new BusinessError('JSON request required.',415);}
export function apiError(error:unknown){if(error instanceof BusinessError)return Response.json({error:error.message},{status:error.status});console.error(error);return Response.json({error:'This service is temporarily unavailable. Your changes have not been confirmed; refresh before retrying.'},{status:503});}
