import {z} from 'zod';
export type Actor={id:string;email:string;name:string;role:'admin'|'customer'|'vendor'};
export type Item={id:string;kind:string;owner:string;event:string;status:string;data:any;created:string;updated:string};
export class BusinessError extends Error{constructor(message:string,public status=400){super(message)}}
const need=(condition:unknown,message:string,status=400)=>{if(!condition)throw new BusinessError(message,status)};
const text=z.string().trim().min(1).max(2000),id=z.string().min(1).max(100),date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(s=>!isNaN(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s,'Invalid date');
const rupees=z.coerce.number().finite().positive().max(10000000).refine(n=>Math.abs(n*100-Math.round(n*100))<0.00001,'Use at most two decimal places');
const category=z.enum(['Catering','Photography','Decoration','Venue','Entertainment','Other']);
const schemas:Record<string,z.ZodTypeAny>={
 create_event:z.object({name:text,phone:z.string().regex(/^\+?[\d ()-]{7,20}$/),type:text,date:date.refine(s=>s>=new Date().toISOString().slice(0,10),'Choose a future date'),city:text,guests:z.coerce.number().int().min(1).max(100000),budget:rupees,services:z.array(category).min(1),notes:z.string().max(2000).default('')}),
 register_vendor:z.object({name:text,phone:z.string().regex(/^\+?[\d ()-]{7,20}$/),city:text,category,portfolio:z.string().url().refine(s=>s.startsWith('https://'),'Use an HTTPS portfolio link'),description:text}),
 review_vendor:z.object({id,status:z.enum(['approved','rejected','suspended']),reason:text}),
 availability:z.object({date,available:z.boolean()}),
 submit_quote:z.object({event:id,amount:rupees,advance:z.coerce.number().min(0).max(100),scope:text,exclusions:z.string().max(2000).default(''),validUntil:date}),
 create_package:z.object({event:id,name:z.enum(['Essential','Signature','Premium']),quotes:z.array(id).min(1).max(20),markup:z.coerce.number().min(0).max(100),inclusions:text,exclusions:text,terms:text,advancePercent:z.coerce.number().min(0).max(100)}),
 publish_package:z.object({id}),approve_package:z.object({id,acknowledge:z.literal(true)}),confirm_event:z.object({id}),complete_event:z.object({id}),
 request_cancellation:z.object({id,reason:text}),resolve_cancellation:z.object({id,decision:z.enum(['cancel','retain']),reason:text}),
 payment:z.object({event:id,type:z.enum(['receipt','refund','vendor_payment']),amount:rupees,reference:z.string().trim().min(3).max(100),vendor:z.string().max(100).default(''),note:text}),
 create_task:z.object({event:id,name:text,assignee:id,due:date,visibility:z.enum(['team','customer']).default('team')}),complete_task:z.object({id}),
 report_issue:z.object({event:id,quote:id,reason:text,evidence:text,amount:rupees}),respond_issue:z.object({id,response:text}),resolve_issue:z.object({id,decision:z.enum(['approved','rejected']),reason:text}),
 read_notification:z.object({id}),support:z.object({subject:text,message:text}),resolve_support:z.object({id,response:text}),
 settings:z.object({supportEmail:z.string().email(),supportPhone:text,privacy:text,cancellation:text,terms:text,published:z.boolean()}),
 deletion_request:z.object({reason:text})
};
export async function dataset(db:D1Database){await db.prepare("INSERT OR IGNORE INTO workspace_state(id,revision,token) VALUES ('josh',0,'')").run();const [state,result,members]=await Promise.all([db.prepare("SELECT revision FROM workspace_state WHERE id='josh'").first<{revision:number}>(),db.prepare('SELECT * FROM business ORDER BY created DESC').all<any>(),db.prepare('SELECT id,name,email,role FROM members').all<any>()]);return {version:state!.revision,items:result.results.map(r=>({...r,data:JSON.parse(r.payload),payload:undefined})) as Item[],members:members.results};}
export function finance(event:Item,items:Item[]){const pkg=items.find(i=>i.id===event.data.packageId);const ledger=items.filter(i=>i.kind==='payment'&&i.event===event.id);const sum=(t:string)=>ledger.filter(i=>i.data.type===t).reduce((n,i)=>n+i.data.amount,0);const received=sum('receipt'),refunds=sum('refund'),paid=sum('vendor_payment'),deductions=items.filter(i=>i.kind==='issue'&&i.event===event.id&&i.status==='approved').reduce((n,i)=>n+i.data.amount,0);return {packageTotal:pkg?.data.total||0,vendorCost:pkg?.data.cost||0,requiredAdvance:pkg?.data.advance||0,received,refunds,paid,deductions,cash:received-refunds-paid,customerBalance:Math.max(0,(pkg?.data.total||0)-received+refunds),vendorOutstanding:Math.max(0,(pkg?.data.cost||0)-deductions-paid),margin:(pkg?.data.total||0)-(pkg?.data.cost||0)+deductions};}
export function visible(actor:Actor,ds:Awaited<ReturnType<typeof dataset>>){if(actor.role==='admin')return {...ds,finances:ds.items.filter(i=>i.kind==='event').map(e=>({event:e.id,...finance(e,ds.items)}))};const ownEvents=new Set(ds.items.filter(i=>i.kind==='event'&&i.owner===actor.id).map(i=>i.id));const ownQuotes=new Set(ds.items.filter(i=>i.kind==='quote'&&i.owner===actor.id).map(i=>i.id));const vendor=ds.items.find(i=>i.kind==='vendor'&&i.owner===actor.id);const assignedEvents=new Set(ds.items.filter(i=>i.kind==='package'&&['approved'].includes(i.status)&&i.data.quotes.some((q:any)=>q.vendor===actor.id)).map(i=>i.event));const items=ds.items.filter(i=>{
 if(['settings'].includes(i.kind))return i.status==='published';
 if(['notification','support','deletion','availability','vendor'].includes(i.kind))return i.owner===actor.id;
 if(actor.role==='customer'){if(i.kind==='event')return ownEvents.has(i.id);if(i.kind==='package')return ownEvents.has(i.event)&&i.status!=='draft';if(i.kind==='payment')return ownEvents.has(i.event)&&i.data.type!=='vendor_payment';if(i.kind==='task')return ownEvents.has(i.event)&&i.data.visibility==='customer';if(i.kind==='issue')return i.owner===actor.id;return false;}
 if(i.kind==='event')return vendor?.status==='approved'&&(['enquiry','quoting'].includes(i.status)||assignedEvents.has(i.id));
 if(i.kind==='quote')return i.owner===actor.id;if(i.kind==='task')return i.data.assignee===actor.id;
 if(i.kind==='issue')return ownQuotes.has(i.data.quote);if(i.kind==='payment')return i.data.vendor===actor.id;return false;
 }).map(i=>{if(i.kind==='event'&&actor.role==='vendor')return {...i,owner:'',data:{name:i.data.type+' in '+i.data.city,type:i.data.type,date:i.data.date,city:i.data.city,guests:i.data.guests,services:i.data.services}};if(i.kind==='package')return {...i,data:{name:i.data.name,total:i.data.total,advance:i.data.advance,inclusions:i.data.inclusions,exclusions:i.data.exclusions,terms:i.data.terms,guests:i.data.guests,eventDate:i.data.eventDate,policySnapshot:i.data.policySnapshot,services:i.data.quotes.map((q:any)=>({id:q.id,category:q.category}))}};return i;});
 return {version:ds.version,items,members:[],finances:[]};}
export async function command(db:D1Database,actor:Actor,input:any){const parsed=schemas[input?.action]?.safeParse(input?.data);need(parsed?.success,parsed&&!parsed.success?parsed.error.issues.map((i:any)=>i.path.join('.')+': '+i.message).join('; '):'Unknown action');const p=parsed!.data,ds=await dataset(db);need(Number.isInteger(input.version)&&input.version===ds.version,'The workspace changed. Refresh and retry.',409);const items=ds.items,action=input.action;const pending:Item[]=[];const updates:Item[]=[];const now=new Date().toISOString(),token=crypto.randomUUID();
 const add=(kind:string,owner:string,event:string,status:string,data:any)=>{const r={id:crypto.randomUUID(),kind,owner,event,status,data,created:now,updated:now};pending.push(r);return r};
 const get=(key:string,kind?:string)=>{const i=items.find(i=>i.id===key&&(!kind||i.kind===kind));need(i,'Record not found',404);return i!};
 const update=(r:Item,status:string,data:any=r.data)=>{const n={...r,status,data,updated:now};updates.push(n);return n};
 const admin=()=>need(actor.role==='admin','Administrator access required',403);
 const eventAccess=(r:Item)=>need(actor.role==='admin'||r.owner===actor.id,'This event is not yours',403);
 const notify=(owner:string,event:string,message:string)=>{if(owner)add('notification',owner,event,'unread',{message})};
 const notifyAdmins=(event:string,message:string)=>ds.members.filter(m=>m.role==='admin').forEach(m=>notify(m.id,event,message));
 let target='';
 if(action==='create_event'){need(actor.role!=='vendor','Use a customer account to request an event',403);const e=add('event',actor.id,'','enquiry',{...p,budget:Math.round(p.budget*100)});target=e.id;notifyAdmins(e.id,'New event enquiry: '+p.name);}
 if(action==='register_vendor'){need(actor.role==='vendor','A vendor account is required',403);need(!items.some(i=>i.kind==='vendor'&&i.owner===actor.id),'A vendor profile already exists');const v=add('vendor',actor.id,'','pending',p);target=v.id;notifyAdmins('','Vendor approval requested: '+p.name);}
 if(action==='review_vendor'){admin();const v=get(p.id,'vendor');target=v.id;update(v,p.status,{...v.data,review:p.reason});notify(v.owner,'','Vendor profile '+p.status+': '+p.reason);}
 if(action==='availability'){need(actor.role==='vendor','Vendor account required',403);const v=items.find(i=>i.kind==='availability'&&i.owner===actor.id&&i.data.date===p.date);if(v)update(v,p.available?'available':'unavailable',p);else add('availability',actor.id,'',p.available?'available':'unavailable',p);}
 if(action==='submit_quote'){need(actor.role==='vendor','Vendor account required',403);const vendor=items.find(i=>i.kind==='vendor'&&i.owner===actor.id);need(vendor?.status==='approved','Your vendor profile must be approved');const e=get(p.event,'event');need(['enquiry','quoting'].includes(e.status),'This event is no longer collecting quotes');need(e.data.services.includes(vendor!.data.category),'This service was not requested');need(!items.some(i=>i.kind==='availability'&&i.owner===actor.id&&i.data.date===e.data.date&&i.status==='unavailable'),'You marked this date unavailable');need(p.validUntil>=new Date().toISOString().slice(0,10),'Quote validity cannot be in the past');need(!items.some(i=>i.kind==='quote'&&i.event===e.id&&i.owner===actor.id),'You already submitted a quote for this event');target=add('quote',actor.id,e.id,'submitted',{...p,amount:Math.round(p.amount*100),vendor:actor.id,vendorName:vendor!.data.name,category:vendor!.data.category}).id;update(e,'quoting');notifyAdmins(e.id,'New '+vendor!.data.category+' quote for '+e.data.name);}
 if(action==='create_package'){admin();const e=get(p.event,'event');need(['enquiry','quoting'].includes(e.status),'Cannot change packages after customer approval');need(new Set(p.quotes).size===p.quotes.length,'Duplicate quotes');const quotes=p.quotes.map((q:string)=>get(q,'quote'));need(quotes.every((q:Item)=>q.event===e.id),'Quotes must belong to this event');need(quotes.every((q:Item)=>q.data.validUntil>=new Date().toISOString().slice(0,10)),'A quote has expired');need(new Set(quotes.map((q:Item)=>q.data.category)).size===quotes.length,'Choose one quote per service category');need(quotes.every((q:Item)=>items.some(v=>v.kind==='vendor'&&v.owner===q.owner&&v.status==='approved')),'A vendor is not approved');const cost=quotes.reduce((n:number,q:Item)=>n+q.data.amount,0),total=Math.round(cost*(1+p.markup/100)),vendorAdvance=quotes.reduce((n:number,q:Item)=>n+Math.ceil(q.data.amount*q.data.advance/100),0);target=add('package',e.owner,e.id,'draft',{...p,quotes:quotes.map((q:Item)=>({id:q.id,vendor:q.owner,category:q.data.category,amount:q.data.amount})),cost,total,advance:Math.max(vendorAdvance,Math.ceil(total*p.advancePercent/100)),guests:e.data.guests,eventDate:e.data.date}).id;}
 if(action==='publish_package'){admin();const pkg=get(p.id,'package'),e=get(pkg.event,'event');need(pkg.status==='draft'&&['enquiry','quoting'].includes(e.status),'Package cannot be published in this state');need(items.some(i=>i.kind==='settings'&&i.status==='published'),'Publish your approved business policies first');update(pkg,'published',{...pkg.data,policySnapshot:items.find(i=>i.kind==='settings'&&i.status==='published')!.data});target=pkg.id;notify(pkg.owner,pkg.event,'Your '+pkg.data.name+' package is ready to review.');}
 if(action==='approve_package'){const pkg=get(p.id,'package'),e=get(pkg.event,'event');eventAccess(e);need(actor.role==='customer'||(actor.role==='admin'&&e.owner===actor.id),'Customer approval is required',403);need(pkg.status==='published'&&['enquiry','quoting'].includes(e.status),'This package is no longer available');need(pkg.data.quotes.every((q:any)=>get(q.id,'quote').data.validUntil>=new Date().toISOString().slice(0,10)),'Quote expired; request an updated package');need(pkg.data.quotes.every((q:any)=>items.some(v=>v.kind==='vendor'&&v.owner===q.vendor&&v.status==='approved')),'A selected vendor is no longer approved');update(pkg,'approved',{...pkg.data,approvedAt:now,approvedBy:actor.id});update(e,'awaiting_advance',{...e.data,packageId:pkg.id});target=e.id;notifyAdmins(e.id,'Customer approved '+pkg.data.name+' for '+e.data.name);}
 if(action==='confirm_event'){admin();const e=get(p.id,'event');need(e.status==='awaiting_advance','Customer approval is required first');const f=finance(e,items);need(f.received-f.refunds>=f.requiredAdvance,'Customer advance has not been received');const pkg=get(e.data.packageId,'package');for(const q of pkg.data.quotes){need(!items.some(i=>i.kind==='availability'&&i.owner===q.vendor&&i.data.date===e.data.date&&i.status==='unavailable'),'A selected vendor is unavailable');need(!items.some(i=>i.kind==='event'&&i.id!==e.id&&['confirmed','completed'].includes(i.status)&&i.data.date===e.data.date&&items.find(k=>k.id===i.data.packageId)?.data.quotes.some((v:any)=>v.vendor===q.vendor)),'A selected vendor is already booked on this date');notify(q.vendor,e.id,'Booking confirmed for '+e.data.date+' in '+e.data.city);}update(e,'confirmed');target=e.id;notify(e.owner,e.id,'Your event booking is confirmed.');}
 if(action==='complete_event'){admin();const e=get(p.id,'event');need(e.status==='confirmed','Only confirmed events can be completed');need(e.data.date<=new Date().toISOString().slice(0,10),'The event date has not arrived');need(!items.some(i=>i.kind==='task'&&i.event===e.id&&i.status!=='complete'),'Complete all responsibilities first');update(e,'completed');target=e.id;notify(e.owner,e.id,'Your event has been marked complete.');}
 if(action==='request_cancellation'){const e=get(p.id,'event');eventAccess(e);need(!['completed','cancelled','cancellation_requested'].includes(e.status),'Cancellation is not available in this state');update(e,'cancellation_requested',{...e.data,previousStatus:e.status,cancellationReason:p.reason});target=e.id;notifyAdmins(e.id,'Cancellation requested for '+e.data.name);}
 if(action==='resolve_cancellation'){admin();const e=get(p.id,'event');need(e.status==='cancellation_requested','No pending cancellation');update(e,p.decision==='cancel'?'cancelled':e.data.previousStatus,{...e.data,cancellationDecision:p.reason});target=e.id;notify(e.owner,e.id,'Cancellation reviewed: '+p.reason);}
 if(action==='payment'){admin();const e=get(p.event,'event');need(e.data.packageId,'Approve a package before recording money');const amount=Math.round(p.amount*100),f=finance(e,items);need(!items.some(i=>i.kind==='payment'&&i.data.reference.toLowerCase()===p.reference.toLowerCase()),'Payment reference already recorded');if(p.type==='receipt'){need(!['cancelled','cancellation_requested'].includes(e.status),'Do not collect money on a cancelled event');need(amount<=f.customerBalance,'Amount exceeds the customer balance');}if(p.type==='refund')need(amount<=f.received-f.refunds&&amount<=f.cash,'Refund exceeds received money or available event cash');if(p.type==='vendor_payment'){need(['confirmed','completed'].includes(e.status),'Confirm the event before paying vendors');const pkg=get(e.data.packageId,'package'),allocation=pkg.data.quotes.filter((q:any)=>q.vendor===p.vendor).reduce((n:number,q:any)=>n+q.amount,0);const paid=items.filter(i=>i.kind==='payment'&&i.event===e.id&&i.data.vendor===p.vendor&&i.data.type==='vendor_payment').reduce((n,i)=>n+i.data.amount,0),deducted=items.filter(i=>i.kind==='issue'&&i.event===e.id&&i.status==='approved'&&get(i.data.quote,'quote').owner===p.vendor).reduce((n,i)=>n+i.data.amount,0);need(amount<=allocation-paid-deducted,'Payment exceeds vendor balance');need(amount<=f.cash,'Insufficient customer funds for this vendor payment');need(!items.some(i=>i.kind==='issue'&&i.event===e.id&&['open','responded'].includes(i.status)&&get(i.data.quote,'quote').owner===p.vendor),'Resolve this vendor’s service issue before settlement');}target=add('payment',e.owner,e.id,'recorded',{...p,amount,recordedBy:actor.id,receiptNumber:'JE-'+crypto.randomUUID().slice(0,8).toUpperCase()}).id;notify(p.type==='vendor_payment'?p.vendor:e.owner,e.id,'Payment record added: '+p.reference);}
 if(action==='create_task'){admin();const e=get(p.event,'event');need(!['completed','cancelled'].includes(e.status),'This event is closed');const assignee=ds.members.find(m=>m.id===p.assignee);need(assignee,'Select a registered assignee');need(assignee.role==='admin'||(assignee.role==='customer'&&e.owner===assignee.id)||(assignee.role==='vendor'&&items.some(i=>i.kind==='quote'&&i.event===e.id&&i.owner===assignee.id)),'Assignee is not part of this event');target=add('task',actor.id,e.id,'pending',p).id;notify(p.assignee,e.id,'New responsibility: '+p.name+' · Due '+p.due);}
 if(action==='complete_task'){const task=get(p.id,'task');need(actor.role==='admin'||task.data.assignee===actor.id,'Only the assignee or administrator can complete this task',403);need(task.status==='pending','Task is already complete');update(task,'complete',{...task.data,completedAt:now,completedBy:actor.id});target=task.id;}
 if(action==='report_issue'){const e=get(p.event,'event');eventAccess(e);need(['confirmed','completed'].includes(e.status),'Issues apply to confirmed or completed bookings');const q=get(p.quote,'quote'),pkg=get(e.data.packageId,'package');need(q.event===e.id&&pkg.data.quotes.some((x:any)=>x.id===q.id),'Quote is not in the booked package');const amount=Math.round(p.amount*100);need(amount<=q.data.amount,'Proposed deduction exceeds the quote');target=add('issue',actor.id,e.id,'open',{...p,amount}).id;notify(q.owner,e.id,'Service issue reported. Please review and respond.');notifyAdmins(e.id,'New service issue for '+e.data.name);}
 if(action==='respond_issue'){const issue=get(p.id,'issue'),q=get(issue.data.quote,'quote');need(actor.role==='vendor'&&q.owner===actor.id,'Only the affected vendor can respond',403);need(['open','responded'].includes(issue.status),'Issue is already resolved');update(issue,'responded',{...issue.data,response:p.response,respondedAt:now});target=issue.id;notifyAdmins(issue.event,'Vendor response received for a service issue.');}
 if(action==='resolve_issue'){admin();const issue=get(p.id,'issue'),q=get(issue.data.quote,'quote');need(issue.status==='responded','Record the vendor response before resolving this issue');if(p.decision==='approved'){const approved=items.filter(i=>i.kind==='issue'&&i.id!==issue.id&&i.data.quote===q.id&&i.status==='approved').reduce((n,i)=>n+i.data.amount,0);const paid=items.filter(i=>i.kind==='payment'&&i.event===q.event&&i.data.type==='vendor_payment'&&i.data.vendor===q.owner).reduce((n,i)=>n+i.data.amount,0);need(approved+issue.data.amount<=q.data.amount-paid,'Deduction exceeds the unpaid vendor balance');}update(issue,p.decision,{...issue.data,decisionReason:p.reason,decidedAt:now,decidedBy:actor.id});target=issue.id;notify(q.owner,issue.event,'Service issue '+p.decision+': '+p.reason);notify(issue.owner,issue.event,'Service issue '+p.decision+': '+p.reason);}
 if(action==='read_notification'){const n=get(p.id,'notification');need(n.owner===actor.id,'Not your notification',403);update(n,'read');target=n.id;}
 if(action==='support'||action==='deletion_request'){target=add(action==='support'?'support':'deletion',actor.id,'','open',p).id;notifyAdmins('',action==='support'?'New support request: '+p.subject:'Account deletion request received');}
 if(action==='resolve_support'){admin();const s=get(p.id,'support');update(s,'resolved',{...s.data,response:p.response});target=s.id;notify(s.owner,'','Support response: '+p.response);}
 if(action==='settings'){admin();const s=items.find(i=>i.kind==='settings');if(s){update(s,p.published?'published':'draft',p);target=s.id}else target=add('settings',actor.id,'',p.published?'published':'draft',p).id;}
 need(pending.length+updates.length>0,'No changes to save');add('audit',actor.id,target,'recorded',{action,target,actorName:actor.name,at:now});
 const gate="EXISTS (SELECT 1 FROM workspace_state WHERE id='josh' AND revision=? AND token=?)";const bindings=[ds.version+1,token];
 const statements=[db.prepare("UPDATE workspace_state SET revision=revision+1,token=? WHERE id='josh' AND revision=?").bind(token,ds.version),...updates.map(i=>db.prepare(`UPDATE business SET status=?,payload=?,updated=? WHERE id=? AND ${gate}`).bind(i.status,JSON.stringify(i.data),now,i.id,...bindings)),...pending.map(i=>db.prepare(`INSERT INTO business(id,kind,owner,event,status,payload,created,updated) SELECT ?,?,?,?,?,?,?,? WHERE ${gate}`).bind(i.id,i.kind,i.owner,i.event,i.status,JSON.stringify(i.data),i.created,i.updated,...bindings))];
 const result=await db.batch(statements);need(result[0].meta.changes===1,'Another update was saved first. Refresh and retry.',409);return {id:target,version:ds.version+1};
}
