import {getChatGPTUser} from '../../chatgpt-auth';
import {recordsDb} from '../../../db/records';
import {schemas} from './validation';
export async function GET(){const user=await getChatGPTUser();if(!user)return Response.json({error:'Sign in to access your private workspace.'},{status:401});try{const result=await recordsDb().prepare('SELECT id,kind,payload,created FROM records WHERE owner = ? ORDER BY created DESC').bind(user.userId).all();return Response.json({records:result.results.map((r:any)=>({...r,data:JSON.parse(r.payload),payload:undefined}))});}catch(e){console.error(e);return Response.json({error:'Your records could not be loaded. Please try again.'},{status:503});}}
export async function POST(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:'Sign in to save to your private workspace.'},{status:401});const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)return Response.json({error:'Invalid origin'},{status:403});try{const raw=await request.text();if(raw.length>16000)return Response.json({error:'Record too large'},{status:413});let payload;try{payload=JSON.parse(raw)}catch{return Response.json({error:'Invalid JSON'},{status:400})}const {kind,data}=payload;const valid=schemas[kind]?.safeParse(data);if(!valid?.success)return Response.json({error:valid&&!valid.success?valid.error.issues.map((i:any)=>i.path.join('.')+': '+i.message).join('; '):'Invalid record type'},{status:400});const clean=valid.data;
const db=recordsDb();async function related(id:string,kind:string){const r=await db.prepare('SELECT payload FROM records WHERE id = ? AND owner = ? AND kind = ?').bind(id,user!.userId,kind).first<{payload:string}>();return r?JSON.parse(r.payload):null;}
if(clean.event&&!await related(clean.event,'event'))return Response.json({error:'Select an event from your workspace.'},{status:400});
if(kind==='quote'&&!await related(clean.vendor,'vendor'))return Response.json({error:'Select a registered vendor.'},{status:400});
if(kind==='package'){const unique=[...new Set(clean.quoteIds)] as string[];const quotes=await Promise.all(unique.map(id=>related(id,'quote')));if(quotes.some(q=>!q||q.event!==clean.event))return Response.json({error:'Select valid quotes for the same event.'},{status:400});const categories=await Promise.all(quotes.map(q=>related(q.vendor,'vendor')));if(new Set(categories.map(v=>v?.category)).size!==quotes.length)return Response.json({error:'Select one quote per service category to avoid duplicate costs.'},{status:400});clean.quoteIds=unique;clean.cost=quotes.reduce((a,q)=>a+q.amount,0);clean.amount=Math.round(clean.cost*(1+clean.fee/100));clean.advance=Math.ceil(quotes.reduce((a,q)=>a+q.amount*q.advance/100,0));}
if(kind==='adjustment'){const q=await related(clean.quote,'quote');if(!q)return Response.json({error:'Select a valid quote.'},{status:400});const existing=await db.prepare("SELECT payload FROM records WHERE owner = ? AND kind = 'adjustment'").bind(user.userId).all<{payload:string}>();const total=existing.results.map(r=>JSON.parse(r.payload)).filter(a=>a.quote===clean.quote).reduce((a,r)=>a+Number(r.amount),0);if(total+clean.amount>q.amount)return Response.json({error:'Total proposed deductions cannot exceed the quote amount.'},{status:400});clean.status='Pending review';}
const id=crypto.randomUUID(),created=new Date().toISOString();await db.prepare('INSERT INTO records (id,owner,kind,payload,created) VALUES (?,?,?,?,?)').bind(id,user.userId,kind,JSON.stringify(clean),created).run();return Response.json({record:{id,kind,data:clean,created}},{status:201});}catch(e){console.error(e);return Response.json({error:'Could not save. Your entries are still here; please retry.'},{status:503});}}
